"""Updated the Transaction schema

Revision ID: 57414c632028
Revises: ec1bfb3bb2a8
Create Date: 2024-07-10 21:01:21.722906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57414c632028'
down_revision = 'ec1bfb3bb2a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('tag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
